policies:
  - name: "KerasPolicy"
    epochs: 25
    validation_split: 0.0
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 5
        state_featurizer:
          - name: BinarySingleStateFeaturizer
  - name: "AugmentedMemoizationPolicy"
    max_history: 5
  - name: "FallbackPolicy"
    fallback_action_name: "utter_doing_greet"
    nlu_threshold: 0.005
    core_threshold: 0.005

language: en

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "extended_spacy_entity_extractor.ExtendedSpacyEntityExtractor"
- name: "extended_duckling_http_extractor.ExtendedDucklingHTTPExtractor"
- name: "intent_classifier_sklearn"
