recipe: default.v1
language: en

policies:
  - name: TEDPolicy
    epochs: 25
    max_history: 5
  - name: AugmentedMemoizationPolicy
    max_history: 5
  - name: RulePolicy
    core_fallback_action_name: "utter_doing_greet"
    core_fallback_threshold: 0.005

pipeline:
- name: SpacyNLP
  model: en_core_web_md
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "DIETClassifier"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "extended_spacy_entity_extractor.ExtendedSpacyEntityExtractor"
- name: "SklearnIntentClassifier"
- name: FallbackClassifier
  threshold: 0.005
  ambiguity_threshold: 0.005
